### PR TITLE
Docker container

### PR DESCRIPTION
**Pull request by Hi-Fi**

### CODE REVIEW

**Comment by samuelpcabral** [comment]
@Hi-Fi Hi, I tried to run the tests here, but when I run it, it looks like it can not read the __init __.robot file. because the test not open a connection. do I need to pass some argument or something on the execution to robot read the __init __.robot?

**Comment by Hi-Fi** [comment]
I think you tried things locally (not through container)?

__init__.robot is only called, if that suite is included in tests. So:
- `robot tests` will execute it, as "parent" suite is "tests"
- `robot tests/` will not execute it, as it's basically saying "suites under tests -directory"

**Comment by samuelpcabral** [comment]
@Hi-Fi i see, now i run the test, but i need to execute only one test, (in others projects) there´s other way to do this? or i can change the __init__.robot content to a suite setup (i think this is a easy way for this situation)

**Comment by Hi-Fi** [comment]
The change I made to structure was made because same thing, that I didn't wanted to have setup suite on each suite (plus that caused some issues with clients, too).

Single test cases can be given as argument like in README: https://github.com/Hi-Fi/Robot-Framework-Mainframe-3270-Library/blob/DockerContainer/README.md#running-with-docker

**Comment by samuelpcabral** [comment]
Ok, but if a need to run with a single robot command inside the test folder trough a cmd. like: "robot Keyword_Exceptions_Test.robot" how i can do this with the __init__.robot file?

**Comment by Hi-Fi** [comment]
I would say it's better to use tags for that. Or make the library to allow opening connection multiple times per run (as now is_terminated is set only to true, and nothing changes it back to false).

**Pull request merged**
