### PR TITLE
Setup continuous integration

### PR DESCRIPTION
**Pull request by robinmatz**
Hi,

this PR is totally optional. I just thought it might be nice to have a continuous integration set up for this repository.

`run-tests.yml` runs the test cases against python3.7 and python3.9 with robotframework versions 3.2, 4.0 and 4.1.
It only runs it against x3270 for now, but in theory we could define a suite where argument `visible` is `False` and we can test against s3270 as well.

With windows, I am not sure though.

I have noticed two things however.
1. Sometimes, the ci fails with the error not connected, see file attached. In this case, rerunning it a bit later solved the issue.
2. As you can see below, I wrapped two test cases with `Run Keyword And Continue On Error`. This is because for some reason, the test cases with utf-8 characters fail on linux: `_ëçá != _Ã«Ã§?`. We should open an issue and investigate the error there.

[Tests results python3.7 rf4.1.zip](https://github.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/files/7697092/Tests.results.python3.7.rf4.1.zip)
 
 
 To get a feel for how it looks like, checkout https://github.com/robinmatz/Robot-Framework-Mainframe-3270-Library/actions/runs/1567060531

### CODE REVIEW

**Comment by samuelpcabral** [comment]
Yes, I know this issue with utf-8 in linux, but right now I don´t have a linux machine and time to fix this.

**Comment by samuelpcabral** [comment]
I'm not sure if it's worth testing against different versions of Robot Framework. Theoretically it is backward compatible and I intend to always be using the latest version.

Testing against different versions of Python I completely agree.

**Comment by robinmatz** [comment]
Hey,
so I changed the .yml to only test against different versions of python.
I tried to solve the problem with the encoding. I could fix it for running tests in Docker with the following Dockerfile build from the project root directory:

```
FROM python:3.8

RUN apt-get update && apt-get install -y \
	x3270 s3270 xvfb locales && \
	locale-gen en_US.UTF-8 && \
	python3 -m pip install -U pip wheel setuptools && \
	python3 -m pip install robotframework robotframework-pythonlibcore six

ENV LANG=en_US.UTF-8 \
	LANGUAGE=en_US:en \
	LC_ALL=en_US.UTF-8

WORKDIR /opt/rf

COPY Mainframe3270 Mainframe3270
COPY tests tests

```

However, I was not able to achieve the same results in GitHub Actions.

**Comment by robinmatz** [comment]
Thanks to [this solution](https://github.com/actions/virtual-environments/issues/762#issuecomment-995015079), test cases with utf-8 characters can now also be executed in the pipeline.

**Pull request merged**
